unpackaged/objects/Account__c.object
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <summarizedField>Order_Line_Item__c.Total__c</summarizedField>
        <summaryForeignKey>Order_Line_Item__c.Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Warranty_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Adds text to the purchase order contract related to warranty conditions.</inlineHelpText>
        <label>Warranty Included</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order ID-{00000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Price__c *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>Item ID-{000000}</displayFormat>
        <label>Order Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/OrderTemplateController.cls
/*
 * OrderTemplateController.cls
 * TODO: Stylize this class to include pagination of line items per this article
 * http://wiki.developerforce.com/page/Creating_Professional_PDF_Documents_with_CSS_and_Visualforce
 */
public with sharing class OrderTemplateController {
	public string Message {get; set;}
	Id m_id 			= null;
	
	public OrderTemplateController(){
		m_id = ApexPages.currentPage().getParameters().get('id');
		if(m_id == null){
			Message = 'Missing id parameter. View an Order record and click on "Preview Order" to see this template in action.';
		}
		else{
			Message = '';
		}
	}
	
	Order__c m_order	= null;
	public Order__c getOrder(){
		if(m_order == null && m_id != null){
			m_order = [SELECT Id, Name, Account__r.Name, Account__r.AccountNumber,
				Account__r.BillingStreet, 
				Account__r.BillingCity, 
				Account__r.BillingCountry,
				Account__r.BillingPostalCode,
				Account__r.BillingState,
				Account__r.ShippingStreet,
				Account__r.ShippingCity, 
				Account__r.ShippingCountry,
				Account__r.ShippingPostalCode,
				Account__r.ShippingState,
				Warranty_Included__c ,
				Opportunity__c, Order_Total__c FROM Order__c WHERE Id = :m_id];
		}
		return m_order;
	}
	
	List<Order_Line_Item__c> m_lineItems = null;
	public List<Order_Line_Item__c> getLineItems() {
		if(m_lineItems == null && m_id != null){ 
			m_lineItems = [select Id, Name, Price__c, Product__c, Product__r.Name, Quantity__c,Total__c, Order__c from Order_Line_Item__c where Order__c=:m_id];
		}
		return m_lineItems;
	}
	
	public static testMethod void tests(){
		Account acct = new Account();
		acct.Name = 'test';
		insert acct;
		
		Order__c order = new Order__c();
		order.Account__c = acct.Id;
		insert order;
		
		Order_Line_Item__c item = new Order_Line_Item__c();		
		item.Quantity__c = 2;
		item.Order__c = order.Id;
		item.Price__c = 100.0;
		insert item;
		
		ApexPages.currentPage().getParameters().put('id', order.Id);
		OrderTemplateController controller = new OrderTemplateController();
		System.assertNotEquals(null, controller.getOrder() );
		System.assertNotEquals(null, controller.getLineItems() );	
		System.assertEquals(1, controller.getLineItems().size() );
	}
}